version: '3.8'
services:
  mediawiki:
    image: mediawiki:latest
    restart: always
    ports:
      - 999:80
    environment:
      - MEDIAWIKI_DB_TYPE=mysql
      - MEDIAWIKI_DB_HOST=db
      - MEDIAWIKI_DB_USER=wikiuser
      - MEDIAWIKI_DB_PASSWORD=<PASSWORD>
      - MEDIAWIKI_DB_NAME=wikidb
    volumes:
      - mediawiki_data:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php 
    networks:
      - mediawiki_net
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=<PASSWORD>
      - MYSQL_DATABASE=wikidb
      - MYSQL_USER=wikiuser
      - MYSQL_PASSWORD=<PASSWORD>
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - mediawiki_net
networks:
  mediawiki_net:

volumes:
  mediawiki_data:
  db_data:
